### ISSUE TITLE
Whitelist tweak does nothing iPhone 11 iOS 16.5

### ISSUE THREAD

**Issue by luizfern12** [Lrdsnow/PureKFD#10]
Applying the tweak does nothing and outputs only one line of log

Behaviour:
https://streamable.com/zyjdh5

Log:
`[*] 2023-09-12 20:22:57.259 PureKFD[280:5992] XPC connection interrupted `

**Comment by luizfern12** [comment]
This also happens in SimpleKFD

**Comment by Lrdsnow** [comment]
It just doesn't work
