### ISSUE TITLE
ipad(11,1) pink screen

### ISSUE THREAD

**Issue by mishavac** [Lrdsnow/PureKFD#100]
ipad mini 5 - 16,2
![изображение](https://github.com/PureKFD/PureKFD/assets/106552893/6fed4a1a-80e6-4963-be87-f0a2e7fdbfcb)
[CrashLog.txt](https://github.com/PureKFD/PureKFD/files/13841585/CrashLog.txt)
[crashlogg.txt](https://github.com/PureKFD/PureKFD/files/13841586/crashlogg.txt)

**Comment by Lrdsnow** [comment]
offsets issue (add your own pls)
