### ISSUE TITLE
m1 16.5.1 not work

### ISSUE THREAD

**Issue by bingdang** [Lrdsnow/PureKFD#105]

**Comment by Lrdsnow** [comment]
offsets issue (add your own pls)

**Comment by HH7H** [comment]
> offsets issue (add your own pls)

Where i can got offsets, or how to extract from my iPad

pls. Help

**Comment by luojunqing** [comment]
> > offsets issue (add your own pls)
> 
> Where i can got offsets, or how to extract from my iPad
> 
> pls. Help

https://github.com/Mikasa-san/KFD-Offsets/blob/main/iPad13%2C5%2016.6.1%2020G81.h
try it your own.
