### ISSUE TITLE
Se 2nd generation install trollstore button crashing my app iOS 16.5.1 (20F75)

### ISSUE THREAD

**Issue by thearchymain** [Lrdsnow/PureKFD#119]
After tapping the install trollstore button, it’s freezing 5 seconds and crashing (chip a13)

**Comment by thearchymain** [comment]
iPhone SE 2nd generation, iOS 16.5.1 (20F75)
Chip a13

**Comment by thearchymain** [comment]
These settings btw
![IMG_2558](https://github.com/PureKFD/PureKFD/assets/155424807/4c2cdf41-8b97-4c4f-addf-79c492ef0774)

**Comment by Lrdsnow** [comment]
Offsets issue also https://github.com/PureKFD/PureKFD/issues/110
