### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by ryanfortner** [Lrdsnow/PureKFD#12]
Hi there,

When building through Xcode I receive the following error:

```
error: Build input files cannot be found: '/Users/ryanfortner/Downloads/PureKFD/PureKFD/Misaka/encryptkey.swift', '/Users/username/Downloads/PureKFD/PureKFD/Misaka/encrypt.swift'. Did you forget to declare these files as outputs of any script phases or custom build rules which produce them? (in target 'PureKFD' from project 'PureKFD')
```

Where can I find this file `encryptkey.swift`?

**Comment by Lrdsnow** [comment]
Due to that nature of how Misaka works (and how they made me swear I wouldn't share the enc files), you have to remove the references to these files and uncomment the dummy function for it, also you'll need to add your own libkfd to build

**Comment by Lrdsnow** [comment]
if your still looking into this its now fully open on [the beta branch](https://github.com/PureKFD/PureKFD.git)
