### ISSUE TITLE
iPad12,1 16.2 offsets appear to exist, and appear to be correct (compared with multiple sources) yet cause a kernel panic

### ISSUE THREAD

**Issue by jonahnm** [Lrdsnow/PureKFD#122]
Title, I also have logs that say something like invalid kernel data, I can send them later.

**Comment by jonahnm** [comment]
This also doesn't happen on Misaka which is a bit strange to me.

**Comment by Lrdsnow** [comment]
https://github.com/PureKFD/PureKFD/issues/110
