### ISSUE TITLE
Ipad with 16G RAM

### ISSUE THREAD

**Issue by pla332** [Lrdsnow/PureKFD#123]
PureKFD crash on 16G RAM iPad is not unsupported, when I run a lot of games and software in the background, pureKFD does not crash and shows "installed". Unfortunately, when I restarted it, it didn't replace the "tips" successfully. M1 16.5.1 iPad with 1T ROM and 16G RAM.

**Comment by Lrdsnow** [comment]
Just keep reinstalling tips and retrying, ipads have a low success rate
