### ISSUE TITLE
[SOLVED] Unsupported iPad14,5-A - iOS 16.5.1

### ISSUE THREAD

**Issue by Dragoy** [Lrdsnow/PureKFD#124]
It doesn't work for me, it says that the application was replaced, but after restarting the device, the Tips application remains the same.

How do I find my offsets if they are lost?

**Comment by Dragoy** [comment]
Thanks, I managed to do this on version 1.0.0. It was all the fault of the stage manager mode turned on.When I turned it off, after rebooting everything opened as expected. I think iPad users need to be warned about this somewhere.

**Comment by Dimethyl-Mercury** [comment]
What is the stage manager mode? How to turn it off?

**Comment by Dragoy** [comment]
> What is the stage manager mode? How to turn it off?

Google it “stage manager mode on iPad” please
