### ISSUE TITLE
A13 - 16.6.1 restart safemode!

### ISSUE THREAD

**Issue by nakheel77** [Lrdsnow/PureKFD#133]
My phone restart safemode when i try install tweak in purekfd, i tried some version but dont work, it same when i try install tweak in misaka, when i apply a change, it dont work, and restart device! Many thanks!

**Comment by Lrdsnow** [comment]
yeah that's because it crashes springboard to respring which triggers safe mode

**Comment by nakheel77** [comment]
> yeah that's because it crashes springboard to respring which triggers safe mode

many thanks for your work. i hope this tool will continue  update in future to better!
