### ISSUE TITLE
"How to Bypass Anti-Cheat Protection in Apps Using the KFD Vulnerability"

### ISSUE THREAD

**Issue by qqwq122825** [Lrdsnow/PureKFD#134]
"Hello, boss! I'd like to ask about the KFD vulnerability. Could you please advise on how to use the KFD vulnerability to access the physical address of an app's data and thereby bypass the app's anti-cheat protection? Normally, using the mach_vm_read_ API to access memory addresses would be detected."

**Comment by imnltsa** [comment]
Here's a video that might help you: https://www.youtube.com/watch?v=TirKBifH3Wg
