### ISSUE TITLE
TabBar background doesn't reappear

### ISSUE THREAD

**Issue by hostedbyjustus** [Lrdsnow/PureKFD#139]
When opening settings or on a tweak page after scrolling to the very bottom, the TabBar background disappears essentially everywhere and it's noticeable on the home page on on tweak pages and only comes back after reopening the app. I feel like this isn't the wanted behaviour. If the TabBar background temporarily disappears, it should also come back.

**Comment by Lrdsnow** [comment]
This is a stock iOS bug, gotta wait for apple to fix it

**Comment by hostedbyjustus** [comment]
Really? Good to know. Is it possible to migrate the issue somehow? It's not very ideal.
