### ISSUE TITLE
File picker

### ISSUE THREAD

**Issue by pengubow** [Lrdsnow/PureKFD#140]
File picker does not work when sideloaded through a dev/enterprise certificate.

**Comment by 8mbe** [comment]
+1

**Comment by Lrdsnow** [comment]
Ez fix: don't use a dev or enterprise certificate

**Comment by Lrdsnow** [comment]
(I'll fix it next update)

**Comment by lewiwiii** [comment]
> Ez fix: don't use a dev or enterprise certificate

don't know if it's relevant but using a personal cert the issue persists
