### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by kaya123k** [Lrdsnow/PureKFD#142]
Can you add a file manager that can edit system files?

**Comment by Lrdsnow** [comment]
(iOS 15-18.1b4) SparseRestore is incapable of reading files 
(iOS 15-16.6.1) KFD can only read files when you redirect things, causing a very unstable file manager 
(iOS 15-16.1.2) MDC can read files fine but all MDC versions have FilzaEscaped which is better anyways
