### ISSUE TITLE
misaka folder not exist!!

### ISSUE THREAD

**Issue by hojeezila** [Lrdsnow/PureKFD#15]
There is a problem when I want to compile the source code either with Xcode or ipabuild.sh that says the misaka folder and it's containing files is missing. would you please help me!

**Comment by Lrdsnow** [comment]
Yes these have been privated files as asked by the misaka devs, just remove the references and it should build

**Comment by Lrdsnow** [comment]
if your still looking into this its now fully open on [the beta branch](https://github.com/PureKFD/PureKFD.git)

**Comment by hojeezila** [comment]
Hello
Thank you for what you did
I have a problem when compiling, can you help me?
![Screenshot 2023-12-26 at 4 10 26 PM](https://github.com/PureKFD/PureKFD/assets/144515531/eba4957a-efb6-4204-a5a7-19d2760d0a94)

**Comment by Lrdsnow** [comment]
You need Xcode 15
