### ISSUE TITLE
A12x and a12z

### ISSUE THREAD

**Issue by Mehranullah2017** [Lrdsnow/PureKFD#16]
A12x and a12z
Ipad pro 2018 and 2020 supported by pure kfd?
How to install trollstore2?

**Comment by 4193883-eng** [comment]
this should be covered by #18

**Comment by Git-Boy-Slim** [comment]
There seems to be a problem with using KDF on A12X/A12Z devices. I can't install Trollstore on my iPad Pro 12.9" 4th Gen A12Z iOS 16.3.1 with PureKDF. Hopefully this can be fixed sometime.

**Comment by Lrdsnow** [comment]
A12X/A12Z is currently unsupported until a developer with one is found.
