### ISSUE TITLE
app group name!

### ISSUE THREAD

**Issue by hojeezila** [Lrdsnow/PureKFD#17]
Would you please tell me how I can get the app groups name of applications from their UUID name? 
when I use compiled .ipa it shows the app groups name  and UUID name of applications. for example "F996CBCF-8D87-40F0-AB1E-7519CB87036B" for UUID name and "group.com.apple.news" for app groups name. but when I compile the source code there isn't any app groups name and there is just UUID name! 
this is your compiled .ipa :
![IMG_0017](https://github.com/Lrdsnow/PureKFD/assets/144515531/8130435f-a330-4e65-8a98-15ef24a10bf2)
 
and this is my compiled application: 
![IMG_0018](https://github.com/Lrdsnow/PureKFD/assets/144515531/86747e8b-99e9-4343-9cc5-bd86cdaea4d5)

**Comment by Lrdsnow** [comment]
Fixed with latest commit.
