### ISSUE TITLE
sorry to disturb, it's possible to support A12x(ipad pro 2018) 16.3.1 to use? 

### ISSUE THREAD

**Issue by camenling** [Lrdsnow/PureKFD#26]
sorry to disturb, it's possible to support A12x(ipad pro 2018) 16.3.1 to use?  i get restart always for using

**Comment by sshrmr** [comment]
![IMG_2927](https://github.com/Lrdsnow/PureKFD/assets/46461110/a801a464-8d31-4338-bcec-8ea99ea8d4c2)

**Comment by camenling** [comment]
Seems like misaka teams in holiday.Misaka still restart always for a12x 16.3.1.  i have found offset and success to use simplekfd. when i try to change purekfd code to install trollstore，i found core code is not opensource.

**Comment by camenling** [comment]
my iPad is now successfully use all feature. but when i use getVnodeAtPathByChdir("/private/var/containers/Bundle/Application/")， it crash. 
so any magic in createFolderAndRedirect2？ Or i support offset， can u add to purekfd？ thanks a lot

**Comment by camenling** [comment]
i just stupid forgetting to init offset, success now use custom simple kfd. thanks a lot
