### ISSUE TITLE
I was successful for ip 14pro 16.6.1, anyone who needs inbox telegram: @hoangle01 , free

### ISSUE THREAD

**Issue by 1gucci280401** [Lrdsnow/PureKFD#29]
![IMG_6814](https://github.com/PureKFD/PureKFD/assets/144563783/74bd83ec-b9a2-4a6b-9cc8-995c111b2963)
![IMG_6815](https://github.com/PureKFD/PureKFD/assets/144563783/9668334b-1063-4a8e-aeeb-11882ad12d60)

**Comment by Lrdsnow** [comment]
Nice success but probably should redirect people to [our discord server](https://discord.gg/purekfd) for better support
