### ISSUE TITLE
Can’t remove dynamic Islands 

### ISSUE THREAD

**Issue by jackson392** [Lrdsnow/PureKFD#3]

**Comment by jackson392** [comment]
Help please

**Comment by Lrdsnow** [comment]
Yes this is due to source location not implementing it, this will be fixed in the next version

**Comment by iAndreimv** [comment]
Use simplekfd and set it to your device in the set subtype section

**Comment by El3-reverse** [comment]
Hi there, just wondering if there is a reason why there is a black box in the middle of the dynamic island, I don’t know if this is my phone or a bug, (iPhone SE 2nd gen)
Edit: the box is seperate from the island, but is on top of it so covers the majority of it

**Comment by Lrdsnow** [comment]
@El3-reverse That's just how it is on iPhone SE's/8's

Closing this as its been fixed with v2
