### ISSUE TITLE
iPhone 14 Pro Max on 16.6.1 (20G81) 

### ISSUE THREAD

**Issue by Tainguyen2022** [Lrdsnow/PureKFD#30]
Hello Sir
iPhone 14 Pro Max on 16.6.1 (20G81)
I can not install trollstore
please revise it
Sincerely 
I will donate a cup of coffee 
many thanks for your consistent efforts 
![IMG_9455](https://github.com/PureKFD/PureKFD/assets/113376604/7e7f3c79-f886-4842-a92f-972f4fa1afc5)
![IMG_9456](https://github.com/PureKFD/PureKFD/assets/113376604/009f0a27-196a-4e95-9dc9-4231faad4fe9)
![IMG_9457](https://github.com/PureKFD/PureKFD/assets/113376604/0794e425-44fe-474d-9d2b-4d0ffc63005e)

**Comment by beck-8** [comment]
close

**Comment by beck-8** [comment]
https://t.me/iOS_TrollStore/1630?comment=822768

**Comment by Tainguyen2022** [comment]
many thanks
Sorry , I can not find any place to donate
I am a new one

**Comment by 1gucci280401** [comment]
hello bạn, bạn làm đc chưa, mình vừa thử đc rồi...add zalo 0345759999 mình gửi video cho

**Comment by Tainguyen2022** [comment]
> hello bạn, bạn làm đc chưa, mình vừa thử đc rồi...add zalo 0345759999 mình gửi video cho

cảm ơn bạn nhé, mình sẽ inbox <3

**Comment by Lrdsnow** [comment]
latest build should fix this
