### ISSUE TITLE
iPhone 11 16.6.1 (Offset in the description)

### ISSUE THREAD

**Issue by Mario2425** [Lrdsnow/PureKFD#35]
[iPhone12,1 16.6.1 20G81.zip](https://github.com/PureKFD/PureKFD/files/13804710/iPhone12.1.16.6.1.20G81.zip)

**Comment by 2682856025** [comment]
你成功了吗 我点安装就闪退

**Comment by Lrdsnow** [comment]
yeah not using those offsets but latest build did fix this device
