### ISSUE TITLE
iPad Air 3rd Gen 16.6b1

### ISSUE THREAD

**Issue by ManGuy-Legend** [Lrdsnow/PureKFD#38]
When i try to click install trollstore helper, it kernel panics, can someone help?

**Comment by TheUser11** [comment]
No offsets. Either wait until they are added, or add them yourself.

**Comment by Lrdsnow** [comment]
latest build should fix this

**Comment by ManGuy-Legend** [comment]
Didnt work still

> latest build should fix this
