### ISSUE TITLE
Problem with Dynamic Island

### ISSUE THREAD

**Issue by D1mar0n** [Lrdsnow/PureKFD#4]
Hello! Installed Dynamic Island. Did not like. Removed. After the reboot, the tweak was not removed, although it is no longer in the list of installed ones. How to remove it now? Help me please.
iPhone 12 Pro / iOS 16.6 Beta 1

**Comment by TheEvilShadoo** [comment]
Same issue here on an iPhone 14 with iOS 16.6 Beta 1.

**Comment by jackson392** [comment]
Same

**Comment by jackson392** [comment]
I need help nowwwwwwww I have stuck with Apples big ass notch on a iphene se

**Comment by jackson392** [comment]
Reboot your phone and you simple KFD to remove it

**Comment by TheEvilShadoo** [comment]
> Reboot your phone and you simple KFD to remove it

After a few tries, resetting the SubType in SimpleKFD worked. Thanks!

**Comment by D1mar0n** [comment]
Write in detail what you did to remove Dinamic Island?Отправлено с iPhone23 авг. 2023 г., в 22:54, TheEvilShadoo ***@***.***> написал(а):﻿

Reboot your phone and you simple KFD to remove it

After a few tries, resetting the SubType in SimpleKFD worked. Thanks!

**Comment by TheEvilShadoo** [comment]
To remove the dynamic island, I installed SimpleKFD. Then, in SimpleKFD, I set the SubType to auto and applied it. After that, the island was gone. Hope this helps.

**Comment by D1mar0n** [comment]
Where can I get SimpleKFD? Give me the link, please.

P.S. SimpleKFD 1.3 https://www.upload.ee/files/15606473/SimpleKFD_v1.3.ipa.html

Отправлено с iPhone

> 24 авг. 2023 г., в 06:36, TheEvilShadoo ***@***.***> написал(а):
> 
> SimpleKFD

**Comment by TheEvilShadoo** [comment]
SimpleKFD v1.4: https://github.com/Lrdsnow/SimpleKFD/releases/tag/1.4

**Comment by Lrdsnow** [comment]
Fixed & Tested with v3
