### ISSUE TITLE
Error on iPhone 8

### ISSUE THREAD

**Issue by Checkm8ra1n** [Lrdsnow/PureKFD#5]
![image](https://github.com/Lrdsnow/PureKFD/assets/110713827/d795ac48-e164-4b3a-8de6-75d8934dd893)
There is wrote that my iPhone is supported (A11 arm64)

**Comment by Lrdsnow** [comment]
Only supported with iOS 15

**Comment by Lrdsnow** [comment]
On the iOS 15 ipa

**Comment by Lrdsnow** [comment]
Also that's SimpleKFD not PureKFD :skull:

**Comment by ExtraBytez** [comment]
XD
