### ISSUE TITLE
A solution for the A12X/Z

### ISSUE THREAD

**Issue by Alohaq** [Lrdsnow/PureKFD#51]
I came across a solution for the A12X/Z. The original text is: 'They were so busy that they were not willing to add the offset even if it was provided to them. I have used Cluckabunga to overwrite mounted Tips with https://github.com/opa334/TrollStore/releases/latest/download/PersistenceHelper_Embedded, and installed trollstore myself. Try to do this by yourself. What you need to change:
fileglob__fg_ops 0x0 -> 0x28
proc__p_fd__fd_ofiles 0x0 -> 0xf8
task__threads__next <-> thread__task_threads__next
for A12x/z', from https://github.com/straight-tamago/misaka/issues/99.
 I wonder if the author could take the time to add this?

**Comment by Lrdsnow** [comment]
this was already known
