### ISSUE TITLE
PureKFD App Missing Options

### ISSUE THREAD

**Issue by CicAway** [Lrdsnow/PureKFD#65]
After the program is opened, it is found that the content of the screenshot of the tutorial does not match... I opened this application missing the screenshot content you provided...! I don't know how to fix it 🙁![image](https://github.com/PureKFD/PureKFD/assets/112789020/8f3c18ca-45ac-4d06-aa4d-cfb4813eb172)

**Comment by 1gucci280401** [comment]
This version needs to be adjusted, just install troll
