### ISSUE TITLE
iPhone SE 2 The plug-in does not work. ios16.3.1

### ISSUE THREAD

**Issue by wwweeer** [Lrdsnow/PureKFD#7]
iPhone SE 2  ios16.3.1 The plug-in does not work.

**Comment by Lrdsnow** [comment]
Gotta give more details

**Comment by wwweeer** [comment]
So what should I do?

**Comment by Lrdsnow** [comment]
What do you mean by "Plug-In" if you mean tweak, then what tweaks are you using, there's only rudimentary support for misaka tweaks so
