### ISSUE TITLE
iPad Pro 11 M1 16GB 1TB, iOS 16.3.1 crash when I install trollhelper

### ISSUE THREAD

**Issue by lolinyaanyaamoe** [Lrdsnow/PureKFD#72]
I tried the latest versions of 4.4, 4.6, and 5.0 for a long time, but I haven't succeeded once. However, on my other 12.9-inch M1 iPad Pro running 16.3, it worked on the first try, which feels very strange.

**Comment by lolinyaanyaamoe** [comment]
I tried the latest versions of 4.4, 4.6, and 5.0 for a long time, but I haven't succeeded once. However, on my other 12.9-inch M1 iPad Pro running 16.3, it worked on the first try, which feels very strange.

**Comment by Lrdsnow** [comment]
offsets issue (add your own pls)
