### ISSUE TITLE
iPad Air 3rd Gen, 11,4 16.6b1 kernel panic

### ISSUE THREAD

**Issue by ManGuy-Legend** [Lrdsnow/PureKFD#74]
When i try to install trollstore or even apply tweaks, the kernel panics, the app used to crash and device panic mixed, but now its just panics

**Comment by AjianNie** [comment]
Yep, all A12 series iPads seem to have been "killed"

**Comment by dxyyyy** [comment]
iPad Air 3, 11,3, 16.6,1, panic too

**Comment by Wangzifu98** [comment]
iPad Air 3, 11,3, 16.5,1, panic too

**Comment by Lrdsnow** [comment]
offsets issue (add your own pls)
