### ISSUE TITLE
iPhone 13 16.6

### ISSUE THREAD

**Issue by murfASM** [Lrdsnow/PureKFD#75]
Used the version Pure uploaded on Discord at 2:48pm 1-2-2023 on a 13 16.6; got the prompt that TSHelper was installed but when opening tips the app opens as normal. After opening it to try installing TSHelper again, the prompt doesn't show and instead crashes unless I delete and sideload again. Tested with force reboot and without.

**Comment by Lrdsnow** [comment]
offsets issue (add your own pls)
