### ISSUE TITLE
3/1/2024Ipad14,2 and Ipad 8,12

### ISSUE THREAD

**Issue by Tainguyen2022** [Lrdsnow/PureKFD#77]
hello Sir
Please help me 
I am trying to install many times 
but It still crashes
Ipad14,2 and Ipad 8,12
ios 16.6.1 
thank you

**Comment by 1gucci280401** [comment]
bạn thử misaka chưa

**Comment by Tainguyen2022** [comment]
Mình thử rồi, vẫn chưa được á 8.0.5

**Comment by Tainguyen2022** [comment]
> bạn thử misaka chưa

mình có thử rồi, mà chưa được á bạn
8.0.5

**Comment by Lrdsnow** [comment]
offsets issue (add your own pls)
