### ISSUE TITLE
iPad 8th gen Panic IpadOS 16.2

### ISSUE THREAD

**Issue by home-gihub** [Lrdsnow/PureKFD#9]
# What Version Of IOS Are You Using:
- `16.2`
# What Device Are You Using:
- `Ipad 8th Generation Wifi (A12)`
# How Did You Apply The Tweaks:
- `By Pressing The Apply Button in the first page`
# What Happend During The Problem:
- `The Screen Flashed Purple For A Split Second Then It Shutdown`
# What Tweaks Were You Using:
- `The Whitelist Tweak From The PureKFD Repo`

**Comment by Lrdsnow** [comment]
Whitelist doesn't work atm
