### ISSUE TITLE
iPad mini 6th gen crashes on 16.6

### ISSUE THREAD

**Issue by AdverseMiller** [Lrdsnow/PureKFD#91]
the pureKFD app just closes when attempting to kopen.

**Comment by reidmex** [comment]
If i click install trollstore helper, it just crashes over and over.
iPad mini6 16.6(ipad 14,1 16.6) with pureKFD v5 beta.

**Comment by setsuna0202** [comment]
same issue

**Comment by Lrdsnow** [comment]
offsets issue (add your own pls)
