### ISSUE TITLE
not work on M1 iPad with 1T and 2T rom 16.5.1

### ISSUE THREAD

**Issue by pla332** [Lrdsnow/PureKFD#99]
It works fine on most M1 iPads (16.5.1）， but not on 1T&2T ROM M1 iPads, it crashes over and over. Is it because the 1T&2T ROM version of the iPad has 16g RAM?

**Comment by lolinyaanyaamoe** [comment]
I think the offset in 13,5 is not right

**Comment by Lrdsnow** [comment]
offsets issue (add your own pls)
